### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by yosmanyga** [fzaninotto/Doctrine2ActiveRecord#29]
Change namespace from `Propel` to `Propel2` to avoid conflicts with Propel1. For example when using it in Symfony2 with willdurand/PropelBundle

**Comment by willdurand** [comment]
Question: Why are you using both Propel1 and Propel2 in the same app ?

**Comment by yosmanyga** [comment]
An application that will be developed with Propel1 (to take advantage of behaviors). And a second version will be migrated progressively to Doctrine2 & Propel2 (when more behaviors for Propel2 are ready). It's a little weird, because it's needed two model layers, one for Propel1 and a second for Doctrine2. Do you think is possible?

**Comment by v3labs** [comment]
Why do you need two model layers? Sounds like an overkill to me.
